# -*- coding: utf-8 -*-
"""Atm

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vHTE-JNoJOGCvMAJOzR-XQiWQk6a0zHa
"""

class Atm:
  def __init__(self):
    self.pin=''
    self.balance=0
    self.menu()
  def menu(self):
    user_input=input('''select the no from following:
                  select 1 for pin create
                  select 2 for balance check
                  select 3 for pin change
                  select 4 for amount withdraw
                  select 5 for exit''')
    if user_input=='1':
      self.pin_create()
    elif user_input=='2':
      self.pin_change()
    elif user_input=='3':
      self.check_balance()
    elif user_input=='4':
      self.amount_withdrawl()
    else:
     print('exit')

  def pin_create(self):
      user_pin=int(input('enter the pin '))
      self.pin=user_pin
      user_balance=int(input('enter the balance'))
      self.balance=user_balance
      print('pin created successfully')
      self.menu()
  def pin_change(self):
      old_pin=int(input('enter your old pin'))
      if old_pin==self.pin:
        new_pin=int(input('enter the new pin'))
        print('pin change successfully')
      else:
        print('your pin is incorrect')
      self.menu()
  def check_balance(self):
      user_pin=int(input('enter your pin'))
      if user_pin==self.pin:
       print('your bank balance is',self.balance)
      else:
        print('your pin is incorrect')
      self.menu()
  def amount_withdrawl(self):
      user_pin=int(input('enter your pin'))
      if user_pin==self.pin:
           amount_withdrawl=int(input('enter the amount of withdrwal'))
      if amount_withdrawl<=self.balance:
          self.balance=self.balance-amount_withdrawl
          print(self.balance)
          self.menu()
      else:
        print('you have insufficient balance')

obj1=Atm()